let referentes = [
  {
    id: 1,
    nombre: "Agustin",
    apellido: "Etchebarne",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/aetchebarne" },
      { red: "facebook", link: "prueba" },
    ],
    pagina: "../pages/referentes/agustin-etchebarne.html",
    foto: "../img/referentes/etchebarne_cuadrado.png",
  },
  {
    id: 2,
    nombre: "Marina",
    apellido: "Kienast",
    redesSociales: [{ red: "twitter", link: "markienast1" }],
    pagina: "../pages/referentes/marina-kienast.html",
    foto: "../img/referentes/marina_cuadrado.jpg",
  },
  {
    id: 3,
    nombre: "Gustavo",
    apellido: "Segré",
    redesSociales: [{ red: "twitter", link: "segregustavo" }],
    pagina: "../pages/referentes/gustavo-segre.html",
    foto: "../img/referentes/segre_cuadrado.png",
  },

  {
    id: 4,
    nombre: "Marcos",
    apellido: "H. Ohlsson",
    redesSociales: [{ red: "twitter", link: "hildingmarcos" }],
    pagina: "../pages/referentes/marcos-hilding-ohlsson.html",
    foto: "../img/referentes/marcos_cuadrado.png",
  },
  {
    id: 5,
    nombre: "Manuel",
    apellido: "Adorni",
    redesSociales: [{ red: "twitter", link: "madorni" }],
    pagina: "../pages/referentes/manuel-adorni.html",
    foto: "../img/referentes/adorni_cuadrado.png",
  },
  {
    id: 6,
    nombre: "Gustavo",
    apellido: "Lazzari",
    redesSociales: [{ red: "twitter", link: "lacha" }],
    pagina: "../pages/referentes/gustavo-lazzari.html",
    foto: "../img/referentes/lazzari_cuadrado.png",
  },
  {
    id: 7,
    nombre: "Constanza",
    apellido: "Mazzina",
    redesSociales: [{ red: "twitter", link: "CMazzina" }],
    pagina: "../pages/referentes/constanza-mazzina.html",
    foto: "../img/referentes/constanza_cuadrado.jpg",
  },
  {
    id: 8,
    nombre: "Fausto",
    apellido: "Spotorno",
    redesSociales: [{ red: "twitter", link: "fspotorno" }],
    pagina: "../pages/referentes/fausto-spotorno.html",
    foto: "../img/referentes/fausto_cuadrado.jpg",
  },
  {
    id: 9,
    nombre: "Miguel",
    apellido: "Boggiano",
    redesSociales: [{ red: "twitter", link: "miguel_boggiano" }],
    pagina: "../pages/referentes/miguel-boggiano.html",
    foto: "../img/referentes/boggiano_cuadrado.png",
  },
  {
    id: 10,
    nombre: "Rodrigo",
    apellido: "López Guerra",
    redesSociales: [{ red: "twitter", link: "rodrilopezg" }],
    pagina: "../pages/referentes/rodrigo-lopez-guerra.html",
    foto: "../img/referentes/rodrigo_cuadrado.jpg",
  },
  {
    id: 11,
    nombre: "Gonzalo",
    apellido: "Blousson",
    redesSociales: [{ red: "twitter", link: "GonBlousson" }],
    pagina: "../pages/referentes/gonzalo-blousson.html",
    foto: "../img/referentes/blousson_cuadrado.png",
  },
  {
    id: 12,
    nombre: "Natalia",
    apellido: "Motyl",
    redesSociales: [{ red: "twitter", link: "naty_motyl" }],
    pagina: "../pages/referentes/natalia-motyl.html",
    foto: "../img/referentes/motyl_cuadrado.jpeg",
  },
  {
    id: 13,
    nombre: "Gabriela",
    apellido: "Malerba",
    redesSociales: [{ red: "twitter", link: "GabrielaMaler" }],
    pagina: "../pages/referentes/gabriela-malerba.html",
    foto: "../img/referentes/gabriela_cuadrado.jpg",
  },
  {
    id: 14,
    nombre: "Pablo",
    apellido: "Abdon Torres",
    redesSociales: [{ red: "twitter", link: "AlberdianoArg" }],
    pagina: "../pages/referentes/abdon-torres.html",
    foto: "../img/referentes/abdon-torres_cuadrado.png",
  },
  {
    id: 15,
    nombre: "Victoria",
    apellido: "Flores Pirán",
    redesSociales: [],
    pagina: "../pages/referentes/vicky-flores-piran.html",
    foto: "../img/referentes/victoria_cuadrado.jpg",
  },
  {
    id: 16,
    nombre: "Ariel",
    apellido: "Aguilar",
    redesSociales: [{ red: "twitter", link: "arielaguilar" }],
    pagina: "../pages/referentes/ariel-aguilar.html",
    foto: "../img/referentes/ariel-aguilar_cuadrado.png",
  },
];
