let referentes = [
  {
    id: 1,
    nombre: "Agustin",
    apellido: "Etchebarne",
    redesSociales: { twitter: "aetchebarne" },
    page: "agustin-etchebarne.html",
    foto: "../img/referentes/etchebarne_cuadrado.png",
  },
  {
    id: 2,
    nombre: "Marina",
    apellido: "Kienast",
    redesSociales: { twitter: "markienast1" },
    page: "marina-kienast.html",
    foto: "../img/referentes/marina_cuadrado.jpg",
  },
  {
    id: 3,
    nombre: "Gustavo",
    apellido: "Segré",
    redesSociales: { twitter: "segregustavo" },
    page: "gustavo-segre.html",
    foto: "../img/referentes/segre_cuadrado.png",
  },

  {
    id: 4,
    nombre: "Marcos",
    apellido: "Hilding Ohlsson",
    redesSociales: { twitter: "hildingmarcos" },
    page: "marcos-hilding-ohlsson.html",
    foto: "../img/referentes/marcos_cuadrado.png",
  },
  {
    id: 5,
    nombre: "Manuel",
    apellido: "Adorni",
    redesSociales: { twitter: "www.twitter.com/madorni" },
    page: "manuel-adorni.html",
    foto: "../img/referentes/adorni_cuadrado.png",
  },
  {
    id: 6,
    nombre: "Gustavo",
    apellido: "Lazzari",
    redesSociales: { twitter: "www.twitter.com/lacha" },
    page: "gustavo-lazzari.html",
    foto: "../img/referentes/lazzari_cuadrado.png",
  },
  {
    id: 7,
    nombre: "Constanza",
    apellido: "Mazzina",
    redesSociales: { twitter: "www.twitter.com/CMazzina" },
    page: "constanza-mazzina.html",
    foto: "../img/referentes/constanza_cuadrado.jpg",
  },
  {
    id: 8,
    nombre: "Fausto",
    apellido: "Spotorno",
    redesSociales: { twitter: "www.twitter.com/fspotorno" },
    page: "fausto-spotorno.html",
    foto: "../img/referentes/fausto_cuadrado.jpg",
  },
  {
    id: 9,
    nombre: "Miguel",
    apellido: "Boggiano",
    redesSociales: { twitter: "www.twitter.com/miguel_boggiano" },
    page: "miguel-boggiano.html",
    foto: "../img/referentes/boggiano_cuadrado.png",
  },
  {
    id: 10,
    nombre: "Rodrigo",
    apellido: "López Guerra",
    redesSociales: { twitter: "www.twitter.com/rodrilopezg" },
    page: "rodrigo-lopez-guerra.html",
    foto: "../img/referentes/rodrigo_cuadrado.jpg",
  },
  {
    id: 11,
    nombre: "Gonzalo",
    apellido: "Blousson",
    redesSociales: { twitter: "www.twitter.com/GonBlousson" },
    page: "gonzalo-blousson.html",
    foto: "../img/referentes/blousson_cuadrado.png",
  },
  {
    id: 12,
    nombre: "Natalia",
    apellido: "Motyl",
    redesSociales: { twitter: "www.twitter.com/naty_motyl" },
    page: "natalia-motyl.html",
    foto: "../img/referentes/motyl_cuadrado.jpeg",
  },
  {
    id: 13,
    nombre: "Gabriela",
    apellido: "Malerba",
    redesSociales: { twitter: "www.twitter.com/Gabrielamaler" },
    page: "gabriela-malerba.html",
    foto: "../img/referentes/gabriela_cuadrado.jpg",
  },
  {
    id: 14,
    nombre: "Pablo",
    apellido: "Abdon Torres",
    redesSociales: { twitter: "www.twitter.com/AlberdianoArg" },
    page: "abdon-torres.html",
    foto: "../img/referentes/abdon-torres_cuadrado.png",
  },
  {
    id: 15,
    nombre: "Victoria",
    apellido: "Flores Pirán",
    redesSociales: {},
    page: "vicky-flores-piran.html",
    foto: "../img/referentes/foto vicky retocada1.jpg",
  },
  {
    id: 16,
    nombre: "Ariel",
    apellido: "Aguilar",
    redesSociales: { twitter: "www.twitter.com/arielaguilar" },
    page: "ariel-aguilar.html",
    foto: "../img/referentes/ariel-aguilar_cuadrado.png",
  },
];
