let referentes = [
  {
    id: 1,
    nombre: "Agustin",
    apellido: "Etchebarne",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/aetchebarne" },
      { red: "instagram", link: "https://instagram.com/agustin.etchebarne" },
      { red: "facebook", link: "https://facebook.com/agustin.etchebarne" },
    ],
    pagina: "../pages/referentes/agustin-etchebarne.html",
    foto: "../img/referentes/etchebarne_cuadrado.png",
  },
  {
    id: 2,
    nombre: "Marina",
    apellido: "Kienast",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/markienast1" },
    ],
    pagina: "../pages/referentes/marina-kienast.html",
    foto: "../img/referentes/marina_cuadrado.jpg",
  },
  {
    id: 3,
    nombre: "Gustavo",
    apellido: "Segré",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/segregustavo" },
      { red: "instagram", link: "https://instagram.com/segre.gustavo" },
      { red: "facebook", link: "https://facebook.com/gustavo.segre" },
      { red: "youtube", link: "https://youtube.com/user/gustavoasegre" },
    ],
    pagina: "../pages/referentes/gustavo-segre.html",
    foto: "../img/referentes/segre_cuadrado.png",
  },

  {
    id: 4,
    nombre: "Marcos",
    apellido: "H. Ohlsson",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/hildingmarcos" },
      { red: "instagram", link: "https://instagram.com/marcoshildingohlsson" },
      { red: "facebook", link: "https://facebook.com/marcosho" },
    ],
    pagina: "../pages/referentes/marcos-hilding-ohlsson.html",
    foto: "../img/referentes/marcos_cuadrado.png",
  },
  {
    id: 5,
    nombre: "Manuel",
    apellido: "Adorni",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/madorni" },
      { red: "instagram", link: "https://instagram.com/madorni" },
      { red: "facebook", link: "https://facebook.com/manueladorniok" },
      {
        red: "youtube",
        link: "https://www.youtube.com/channel/UC0fYblcXqZP0NBlPIJzpoDg",
      },
    ],
    pagina: "../pages/referentes/manuel-adorni.html",
    foto: "../img/referentes/adorni_cuadrado.png",
  },
  {
    id: 6,
    nombre: "Gustavo",
    apellido: "Lazzari",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/lacha" },
      { red: "instagram", link: "https://instagram.com/gdlazzari" },
      { red: "facebook", link: "https://facebook.com/gustavo.lazzari" },
    ],
    pagina: "../pages/referentes/gustavo-lazzari.html",
    foto: "../img/referentes/lazzari_cuadrado.png",
  },
  {
    id: 7,
    nombre: "Constanza",
    apellido: "Mazzina",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/cmazzina" },
      { red: "instagram", link: "https://instagram.com/conimazzina" },
      { red: "facebook", link: "https://facebook.com/constanza.mazzina" },
    ],
    pagina: "../pages/referentes/constanza-mazzina.html",
    foto: "../img/referentes/constanza_cuadrado.jpg",
  },
  {
    id: 8,
    nombre: "Fausto",
    apellido: "Spotorno",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/fspotorno" },
      { red: "instagram", link: "https://instagram.com/fspotorno" },
      { red: "facebook", link: "https://facebook.com/fspotorno" },
    ],
    pagina: "../pages/referentes/fausto-spotorno.html",
    foto: "../img/referentes/fausto_cuadrado.jpg",
  },
  {
    id: 9,
    nombre: "Miguel",
    apellido: "Boggiano",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/miguel_boggiano" },
      { red: "instagram", link: "https://instagram.com/miguel_boggiano" },
    ],
    pagina: "../pages/referentes/miguel-boggiano.html",
    foto: "../img/referentes/boggiano_cuadrado.png",
  },
  {
    id: 10,
    nombre: "Rodrigo",
    apellido: "López Guerra",
    redesSociales: [{ red: "twitter", link: "rodrilopezg" }],
    pagina: "../pages/referentes/rodrigo-lopez-guerra.html",
    foto: "../img/referentes/rodrigo_cuadrado.jpg",
  },
  {
    id: 11,
    nombre: "Gonzalo",
    apellido: "Blousson",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/GonBlousson" },
      { red: "instagram", link: "https://instagram.com/gonzaloblousson" },
      { red: "facebook", link: "https://facebook.com/gonzalo.blousson" },
    ],
    pagina: "../pages/referentes/gonzalo-blousson.html",
    foto: "../img/referentes/blousson_cuadrado.png",
  },
  {
    id: 12,
    nombre: "Natalia",
    apellido: "Motyl",
    redesSociales: [
      { red: "twitter", link: "naty_motyl" },
      { red: "instagram", link: "https://instagram.com/naty_motyl" },
    ],
    pagina: "../pages/referentes/natalia-motyl.html",
    foto: "../img/referentes/motyl_cuadrado.jpeg",
  },
  {
    id: 13,
    nombre: "Gabriela",
    apellido: "Malerba",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/GabrielaMaler" },
      { red: "instagram", link: "https://instagram.com/GabrielaMalerba" },
    ],
    pagina: "../pages/referentes/gabriela-malerba.html",
    foto: "../img/referentes/gabriela_cuadrado.jpg",
  },
  {
    id: 14,
    nombre: "Pablo",
    apellido: "Abdon Torres",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/AlberdianoArg" },
      { red: "instagram", link: "https://instagram.com/alberdianoarg" },
    ],
    pagina: "../pages/referentes/abdon-torres.html",
    foto: "../img/referentes/abdon-torres_cuadrado.png",
  },
  {
    id: 15,
    nombre: "Victoria",
    apellido: "Flores Pirán",
    redesSociales: [
      { red: "instagram", link: "https://instagram.com/victorina_flowers" },
    ],
    pagina: "../pages/referentes/vicky-flores-piran.html",
    foto: "../img/referentes/victoria_cuadrado.jpg",
  },
  {
    id: 16,
    nombre: "Ariel",
    apellido: "Aguilar",
    redesSociales: [
      { red: "twitter", link: "https://twitter.com/arielaguilar" },
    ],
    pagina: "../pages/referentes/ariel-aguilar.html",
    foto: "../img/referentes/ariel-aguilar_cuadrado.png",
  },
];

let staffes = [
  {
    id: 1,
    nombre: "Tomás",
    apellido: "Castro",
    foto: "../img/staffes/tomas_castro_cuadrado.png",
    rol: "Contenido, comunicación y redes sociales.",
  },
  {
    id: 2,
    nombre: "Nicolás",
    apellido: "Laurence",
    foto: "../img/staffes/nicolas_laurence_cuadrado.png",
    rol: "Coordinación de voluntarios, logística y afiliaciones.",
  },
  {
    id: 3,
    nombre: "Francisco",
    apellido: "Pelaez",
    foto: "../img/staffes/francisco_pelaez_cuadrado.png",
    rol: "Desarrollo institucional y logística de afiliaciones.",
  },
];
